/**
 *
 * LessonListContainer constants
 *
 */

export const REQUEST_LESSONS = "LessonListContainer/REQUEST_LESSONS";
export const REQUEST_LESSONS_SUCCEEDED =
  "LessonListContainer/REQUEST_LESSONS_SUCCEEDED";
export const REQUEST_LESSON_FAILED =
  "LessonListContainer/REQUEST_LESSON_FAILED";
export const SET_VISIBLE_DELETE_LESSON_MODAL =
  "Dashboard/SET_VISIBLE_DELETE_LESSON_MODAL";
export const SET_INVISIBLE_DELETE_LESSON_MODAL =
  "Dasbhoard/SET_INVISIBLE_DELETE_LESSON_MODAL";
export const REQUEST_DELETE_LESSON = "Dashboard/REQUEST_DELETE_LESSON";
export const REQUEST_DELETE_LESSON_SUCCESS =
  "Dashboard/REQUEST_DELETE_LESSON_SUCCESS";
export const REQUEST_DELETE_LESSON_ERROR =
  "Dashboard/REQUEST_DELETE_LESSON_ERROR";
