export const REQUEST_LESSON_TO_TRAIN = "TrainingMode/REQUEST_LESSON_TO_TRAIN";
export const REQUEST_LESSON_TO_TRAIN_SUCCESS =
  "TrainingMode/REQUEST_LESSON_TO_TRAIN_SUCCESS";
export const SHOW_ANSWER = "TrainingMode/SHOW_ANSWER";
